### ISSUE TITLE
Support reading from custom file in HCL configs

### ISSUE THREAD

**Issue by yeweidaniel** [GoogleCloudPlatform/solution-acceleration-toolkit#1083]
Sometimes we need to provide a custom HL7 parser config to the the HL7 store, such as this example here: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/4276c1ae548ea7b872c1d996ad6ce72bf19ec91f/examples/tfengine/modules/team.hcl#L444 

This custom config is a JSON file that could be several thousand lines long. It would be impractical to copy paste the entire JSON file into a HCL config file, can we have a custom function that reads a separate config file, something like [templatefile](https://www.terraform.io/docs/language/functions/templatefile.html) in Terraform?

**Comment by xingao267** [comment]
Fixed by https://github.com/GoogleCloudPlatform/solution-acceleration-toolkit/pull/1112
